# 04 — Fundamental Analysis Engine

Phase 4 of the Indian Equity AI project plan.

For each of the 5 stocks:
1. Download income statement, balance sheet, cash flow (Yahoo Finance)
2. Compute ratios: ROE, ROCE, Debt/Equity, Current Ratio, Interest Coverage
3. Compute growth metrics (revenue/EBITDA/EPS/FCF YoY and CAGR)
4. Pull snapshot valuation ratios (P/E, P/B, P/S, EV/EBITDA, dividend yield) and ownership %
5. Combine into a single Fundamental Score (0-100)

**Data-source note:** bank income statements (HDFCBANK) don't report EBIT/EBITDA or a
current-assets/current-liabilities split, so ROCE/current ratio/interest coverage are
NaN for it -- this is expected, not a bug. The Fundamental Score itself only depends on
ROE, Debt/Equity, revenue growth, and P/E, all of which are available for every stock,
including HDFCBANK.

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd

from src.fundamentals.statements import download_statements
from src.fundamentals.ratios import (
    add_growth_metrics,
    build_annual_fundamentals,
    cagr,
    snapshot_valuation_and_ownership,
)
from src.fundamentals.score import fundamental_score

DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
from src.config import UNIVERSE  # Phase 14: centralized, now 50 stocks

## Step 1-3: Download statements, compute ratios and growth metrics, per stock

In [2]:
# Phase 14 (50-stock scale-out): a per-stock try/except is now needed -- with only
# 5 hand-picked large caps, every stock had clean, complete Yahoo Finance data; across
# 50 (including a newly-demerged entity, TMPV), some Ticker fetches may fail outright.
# Failures are collected and reported, not silently swallowed, and don't abort the run.
annual_by_symbol = {}
snapshot_by_symbol = {}
fetch_failures = {}

for symbol in UNIVERSE:
    try:
        statements = download_statements(symbol)
        annual = build_annual_fundamentals(statements)
        annual = add_growth_metrics(annual)
        annual_by_symbol[symbol] = annual
        snapshot_by_symbol[symbol] = snapshot_valuation_and_ownership(statements["info"])
        print(symbol, "fiscal years:", [d.date() for d in annual.index])
    except Exception as exc:
        fetch_failures[symbol] = str(exc)
        print(symbol, "FAILED:", exc)

print()
print(f"{len(annual_by_symbol)}/{len(UNIVERSE)} stocks fetched successfully.")
if fetch_failures:
    print("Failed:", fetch_failures)

RELIANCE fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

TCS fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

HDFCBANK fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

ICICIBANK fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

INFY fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

HINDUNILVR fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

ITC fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

SBIN fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

BHARTIARTL fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

BAJFINANCE fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

KOTAKBANK fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

LT fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

HCLTECH fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

AXISBANK fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

ASIANPAINT fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

MARUTI fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

SUNPHARMA fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

TITAN fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

ULTRACEMCO fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

WIPRO fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()
D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()
D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

NESTLEIND fiscal years: [datetime.date(2021, 12, 31), datetime.date(2022, 12, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

ADANIENT fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

ADANIPORTS fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

BAJAJFINSV fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

NTPC fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

POWERGRID fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

M&M fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

TATASTEEL fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

TMPV fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

JSWSTEEL fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

HDFCLIFE fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

SBILIFE fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

GRASIM fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

TECHM fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:69: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  annual[f"{col}_growth_yoy"] = annual[col].pct_change()

INDUSINDBK fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

CIPLA fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

DRREDDY fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

EICHERMOT fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

BRITANNIA fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

DIVISLAB fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

COALINDIA fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

BPCL fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

HEROMOTOCO fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

APOLLOHOSP fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

UPL fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

BAJAJ-AUTO fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

TATACONSUM fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

ONGC fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

HINDALCO fiscal years: [datetime.date(2022, 3, 31), datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

DMART fiscal years: [datetime.date(2023, 3, 31), datetime.date(2024, 3, 31), datetime.date(2025, 3, 31), datetime.date(2026, 3, 31)]

50/50 stocks fetched successfully.

In [3]:
annual_by_symbol["RELIANCE"][
    ["revenue", "net_income", "roe", "roce", "debt_to_equity", "current_ratio", "revenue_growth_yoy"]
]

,revenue,net_income,roe,roce,debt_to_equity,current_ratio,revenue_growth_yoy
2022-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-03-31,8.778350e+12,6.670200e+11,0.093176,0.109730,0.467111,1.074677,NaN
2024-03-31,9.010640e+12,6.962100e+11,0.087741,0.112791,0.436232,1.183037,0.026462
2025-03-31,9.646930e+12,6.964800e+11,0.082600,0.107613,0.438301,1.100351,0.070615
2026-03-31,1.057219e+13,8.077500e+11,0.089350,0.115153,0.440251,1.097912,0.095912

In [4]:
annual_by_symbol["HDFCBANK"][
    ["revenue", "net_income", "roe", "roce", "debt_to_equity", "current_ratio", "revenue_growth_yoy"]
]

,revenue,net_income,roe,roce,debt_to_equity,current_ratio,revenue_growth_yoy
2022-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-03-31,1.205375e+12,4.954469e+11,0.170128,NaN,1.082272,NaN,NaN
2024-03-31,1.604968e+12,6.226566e+11,0.089625,NaN,1.164988,NaN,0.331510
2025-03-31,1.838641e+12,6.735083e+11,0.087732,NaN,0.954306,NaN,0.145593
2026-03-31,1.925668e+12,7.047934e+11,0.086294,NaN,0.813434,NaN,0.047332

## Step 3b: CAGR over the available fiscal-year window

In [5]:
cagr_rows = []
for symbol, annual in annual_by_symbol.items():
    cagr_rows.append(
        {
            "symbol": symbol,
            "revenue_cagr": cagr(annual["revenue"]),
            "eps_cagr": cagr(annual["eps_diluted"]),
            "fcf_cagr": cagr(annual["free_cash_flow"]),
        }
    )
cagr_table = pd.DataFrame(cagr_rows).set_index("symbol")
cagr_table

D:\Practise\Stock Market Analysis\src\fundamentals\ratios.py:82: RuntimeWarning: invalid value encountered in scalar power
  return (clean.iloc[-1] / clean.iloc[0]) ** (1 / years) - 1

            revenue_cagr  eps_cagr  fcf_cagr
symbol
RELIANCE        0.063941  0.065859       NaN
TCS             0.058018  0.056944  0.072516
HDFCBANK        0.169014  0.010489  0.349581
ICICIBANK       0.181134  0.160501       NaN
INFY            0.034419  0.040584  0.137847
HINDUNILVR      0.023053  0.141130  0.030824
ITC             0.036465  0.022145  0.003025
SBIN            0.121870  0.134983       NaN
BHARTIARTL      0.148823  0.449472  0.248686
BAJFINANCE      0.225767  0.171901       NaN
KOTAKBANK       0.134831  0.089627       NaN
LT              0.160914  0.162229 -0.138068
HCLTECH         0.086548  0.038472  0.043077
AXISBANK        0.121605  0.340901       NaN
ASIANPAINT      0.011046  0.017518  0.267911
MARUTI          0.158952  0.211093  0.468174
SUNPHARMA       0.103907  0.106329  0.452689
TITAN           0.292362  0.160106  0.709733
ULTRACEMCO      0.119163  0.164849  0.252653
WIPRO           0.007809  0.066980  0.049211
NESTLEIND       0.170079  0.230343 -0.214645
ADANIENT       -0.076703  0.516143       NaN
ADANIPORTS      0.229293  0.333076  0.222188
BAJAJFINSV      0.229194  0.151039       NaN
NTPC            0.018681  0.169551 -0.325541
POWERGRID       0.005726  0.010937 -0.514764
M&M             0.174973  0.182822       NaN
TATASTEEL      -0.015899  0.064549  0.395793
TMPV           -0.009314       NaN       NaN
JSWSTEEL        0.036139  0.746120  0.071272
HDFCLIFE        0.092531  0.113932  0.486867
SBILIFE         0.110650  0.127427  0.062930
GRASIM          0.143018 -0.109241       NaN
TECHM           0.021581 -0.002144  0.063186
INDUSINDBK     -0.004463 -0.508145       NaN
CIPLA           0.072341  0.114326 -0.251776
DRREDDY         0.109627 -0.017217 -0.229094
EICHERMOT       0.174675  0.235712  0.181476
BRITANNIA       0.056648  0.029517  0.098571
DIVISLAB        0.109757  0.120949 -0.521195
COALINDIA       0.093058 -0.007034  0.145849
BPCL           -0.011539  1.294879  1.000177
HEROMOTOCO      0.117231  0.268443  0.531205
APOLLOHOSP      0.148467  0.333004  0.532310
UPL            -0.011621 -0.202009  0.003573
BAJAJ-AUTO      0.194942  0.218451 -0.233823
TATACONSUM      0.138741  0.066041  0.197351
ONGC           -0.013000  0.041123  0.186816
HINDALCO        0.070996  0.098941       NaN
DMART           0.171360  0.077355       NaN

## Step 4-5: Build the latest-fiscal-year snapshot table and Fundamental Score

In [6]:
rows = []
for symbol in annual_by_symbol:  # only successfully-fetched stocks
    latest = annual_by_symbol[symbol].iloc[-1].to_dict()
    latest.update(snapshot_by_symbol[symbol])
    latest["symbol"] = symbol
    # Website audit (fundamentals metadata gap): record which fiscal year the
    # balance-sheet-basis ratios (roe/roce/debt_to_equity/...) come from, and
    # which day the valuation-basis ratios (pe_ratio/pb_ratio/...) were fetched --
    # these are two different "as of" bases, previously conflated with no period
    # label at all.
    latest["fiscal_year"] = str(annual_by_symbol[symbol].index[-1])
    latest["valuation_as_of"] = pd.Timestamp.now().normalize().date().isoformat()
    rows.append(latest)

fundamentals_snapshot = pd.DataFrame(rows).set_index("symbol")
fundamentals_snapshot["fundamental_score"] = fundamental_score(fundamentals_snapshot)
fundamentals_snapshot[
    ["fiscal_year", "roe", "debt_to_equity", "revenue_growth_yoy", "valuation_as_of", "pe_ratio", "fundamental_score"]
]

,fiscal_year,roe,debt_to_equity,revenue_growth_yoy,valuation_as_of,pe_ratio,fundamental_score
symbol,,,,,,,
RELIANCE,2026-03-31 00:00:00,0.089350,0.440251,0.095912,2026-10-01,21.503622,48.971152
TCS,2026-03-31 00:00:00,0.458877,0.105213,0.045812,2026-10-01,14.903701,74.612212
HDFCBANK,2026-03-31 00:00:00,0.086294,0.813434,0.047332,2026-10-01,15.490710,45.849225
ICICIBANK,2026-03-31 00:00:00,0.149308,0.571853,0.091307,2026-10-01,17.076227,53.648694
INFY,2026-03-31 00:00:00,0.338545,0.098815,0.045702,2026-10-01,12.813868,72.152792
HINDUNILVR,2026-03-31 00:00:00,0.308589,0.030325,0.052664,2026-10-01,41.832146,54.435386
ITC,2026-03-31 00:00:00,0.285343,0.033091,0.047687,2026-10-01,16.577286,67.379783
SBIN,2026-03-31 00:00:00,0.139732,1.219350,0.092085,2026-10-01,10.264227,49.246452
BHARTIARTL,2026-03-31 00:00:00,0.179094,1.310990,0.219600,2026-10-01,36.718914,39.340049
BAJFINANCE,2026-03-31 00:00:00,0.166821,3.095173,0.197347,2026-10-01,28.468843,34.189400
KOTAKBANK,2026-03-31 00:00:00,0.106430,0.526379,-0.002579,2026-10-01,20.461237,45.509765
LT,2026-03-31 00:00:00,0.147168,1.148296,0.118078,2026-10-01,31.146454,38.631048
HCLTECH,2026-03-31 00:00:00,0.221406,0.069381,0.111819,2026-10-01,19.135035,64.003702
AXISBANK,2026-03-31 00:00:00,0.122700,1.304486,0.040145,2026-10-01,13.779925,42.756251
ASIANPAINT,2026-03-31 00:00:00,0.202388,0.183839,0.051034,2026-10-01,48.293470,45.811012
MARUTI,2026-03-31 00:00:00,0.136991,0.000957,0.200894,2026-10-01,26.238820,58.854649
SUNPHARMA,2026-03-31 00:00:00,0.137363,0.055371,0.118730,2026-10-01,36.072277,48.628288
TITAN,2026-03-31 00:00:00,0.323059,1.950010,0.447892,2026-10-01,70.084040,45.816086
ULTRACEMCO,2026-03-31 00:00:00,0.106568,0.310023,0.166102,2026-10-01,37.775402,44.429836
WIPRO,2026-03-31 00:00:00,0.149061,0.229182,0.039686,2026-10-01,12.450904,58.656674
NESTLEIND,2026-03-31 00:00:00,NaN,NaN,0.000000,2026-10-01,66.228510,NaN
ADANIENT,2026-03-31 00:00:00,0.115408,1.317523,0.026158,2026-10-01,51.542690,25.167195
ADANIPORTS,2026-03-31 00:00:00,0.133224,0.657851,0.271053,2026-10-01,30.651102,50.573650
BAJAJFINSV,2026-03-31 00:00:00,0.125790,4.638108,0.136255,2026-10-01,27.380575,29.759661
NTPC,2026-03-31 00:00:00,0.133148,1.333844,-0.011979,2026-10-01,9.792172,43.362846
POWERGRID,2026-03-31 00:00:00,0.158496,1.508130,0.015713,2026-10-01,12.757101,42.069246
M&M,2026-03-31 00:00:00,0.183668,1.438973,0.240629,2026-10-01,18.229006,50.458499
TATASTEEL,2026-03-31 00:00:00,0.105649,0.904217,0.062042,2026-10-01,20.848415,43.188471
TMPV,2026-03-31 00:00:00,0.735179,0.726300,-0.082817,2026-10-01,NaN,NaN
JSWSTEEL,2026-03-31 00:00:00,0.223042,1.190159,0.092823,2026-10-01,12.363386,53.536966
HDFCLIFE,2026-03-31 00:00:00,0.107739,0.174596,0.017072,2026-10-01,57.086530,38.595930
SBILIFE,2026-03-31 00:00:00,0.129430,NaN,-0.042754,2026-10-01,65.624756,NaN
GRASIM,2026-03-31 00:00:00,0.047999,2.202012,0.181727,2026-10-01,36.581840,21.041594
TECHM,2026-03-31 00:00:00,0.162446,0.073820,0.072225,2026-10-01,26.343994,54.107850
INDUSINDBK,2026-03-31 00:00:00,0.013528,0.650889,-0.051653,2026-10-01,53.085987,23.890517
CIPLA,2026-03-31 00:00:00,0.112664,0.017826,0.020861,2026-10-01,32.316925,45.823138
DRREDDY,2026-03-31 00:00:00,0.113641,0.205114,0.031941,2026-10-01,31.018867,44.816092
EICHERMOT,2026-03-31 00:00:00,0.219729,0.020476,0.239471,2026-10-01,33.992584,60.543029
BRITANNIA,2026-03-31 00:00:00,0.496125,0.273689,0.075460,2026-10-01,44.598335,58.056380
DIVISLAB,2026-03-31 00:00:00,0.153213,0.000418,0.123432,2026-10-01,84.207910,48.046899
COALINDIA,2026-03-31 00:00:00,0.261074,0.118153,0.000732,2026-10-01,8.410845,67.947242
BPCL,2026-03-31 00:00:00,0.257995,0.543319,0.026359,2026-10-01,7.559212,64.040351
HEROMOTOCO,2026-03-31 00:00:00,0.265683,0.036028,0.155626,2026-10-01,19.247860,68.942675
APOLLOHOSP,2026-03-31 00:00:00,0.204819,0.895813,0.157195,2026-10-01,56.356550,41.486636
UPL,2026-03-31 00:00:00,0.055395,0.679502,0.108966,2026-10-01,22.148132,43.999454
BAJAJ-AUTO,2026-03-31 00:00:00,0.276685,0.583021,0.225699,2026-10-01,25.856617,61.582079
TATACONSUM,2026-03-31 00:00:00,0.070788,0.129409,0.152053,2026-10-01,57.510597,42.475506
ONGC,2026-03-31 00:00:00,0.111425,0.468839,-0.006037,2026-10-01,6.527898,55.105446
HINDALCO,2026-03-31 00:00:00,0.098043,0.726013,0.150281,2026-10-01,12.771901,53.665145
DMART,2026-03-31 00:00:00,0.121423,0.099125,0.159562,2026-10-01,81.261220,46.331604

## Step 6: Save fundamentals

In [7]:
# Phase 14: a hard assert here would abort the whole run over one stock's data gap.
# Report which stocks (if any) lack a computable score instead of failing the notebook --
# an honest, visible gap is reported, not silently dropped or force-fabricated.
missing_score = fundamentals_snapshot[fundamentals_snapshot["fundamental_score"].isna()]
if not missing_score.empty:
    print(f"WARNING: {len(missing_score)} stock(s) have no computable Fundamental Score:",
          missing_score.index.tolist())

fundamentals_snapshot.to_csv(DATA_PROCESSED / "fundamentals_snapshot.csv")

annual_long = pd.concat(
    [df.assign(symbol=symbol) for symbol, df in annual_by_symbol.items()]
).reset_index(names="fiscal_year_end")
annual_long.to_parquet(DATA_PROCESSED / "fundamentals_annual.parquet", index=False)

print("Saved:", DATA_PROCESSED / "fundamentals_snapshot.csv")
print("Saved:", DATA_PROCESSED / "fundamentals_annual.parquet")

WARNING: 3 stock(s) have no computable Fundamental Score: ['NESTLEIND', 'TMPV', 'SBILIFE']
Saved: D:\Practise\Stock Market Analysis\data\processed\fundamentals_snapshot.csv
Saved: D:\Practise\Stock Market Analysis\data\processed\fundamentals_annual.parquet